trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'client'
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'
  workingDirectory: 'client'

- script: |
    npm test
  displayName: 'Test javascript'
  workingDirectory: 'client'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)\drop' 
    artifactName: 'drop' 
    publishLocation: 'Container'
  displayName: "Publish api artifacts"

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: build
    pathtoPublish: '$(Build.ArtifactStagingDirectory)\build' 